# Generated by Django 5.2.6 on 2026-03-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='form_data',
            field=models.JSONField(blank=True, help_text='Stored form data for offline payments', null=True),
        ),
    ]
