# Generated by Django 5.2.6 on 2026-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_admin_notes_payment_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_transfer_id',
            field=models.CharField(blank=True, help_text='ID of the transfer to the linked account', max_length=100, null=True),
        ),
    ]
