# Generated by Django 5.2.6 on 2026-03-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='average_service_time',
            field=models.PositiveIntegerField(default=5, help_text='Average time in minutes per token'),
        ),
    ]
