# Generated by Django 5.2.6 on 2026-03-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_offline_payment_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
