# Generated by Django 5.2.6 on 2026-03-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_service_is_offline_payment_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='razorpay_account_id',
            field=models.CharField(blank=True, help_text='Linked Razorpay account ID for transfers', max_length=100, null=True),
        ),
    ]
