# Generated by Django 5.2.6 on 2026-03-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_offline_payment_available',
            field=models.BooleanField(default=False),
        ),
    ]
