# Generated by Django 5.2.6 on 2026-03-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_is_offline_payment_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_online_payment_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
