# Generated by Django 5.2.6 on 2026-03-17 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_service_is_online_payment_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='upi_id',
            field=models.CharField(blank=True, help_text='VPA / UPI ID for direct payments', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='upi_qr_code',
            field=models.ImageField(blank=True, help_text='Static QR code for UPI payments', null=True, upload_to='upi_qrs/'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_upi_payment_allowed',
            field=models.BooleanField(default=False, help_text='Allow direct UPI ID/QR payment'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='razorpay_account_id',
            field=models.CharField(blank=True, help_text="Linked Razorpay account ID for transfers (must be 18 characters starting with 'acc_')", max_length=100, null=True, validators=[django.core.validators.RegexValidator(message="Razorpay account ID must be 18 characters starting with 'acc_'", regex='^acc_[a-zA-Z0-9]{14}$')]),
        ),
    ]
