# Generated by Django 5.2.6 on 2026-03-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_upi_id_organization_upi_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='is_upi_payment_allowed',
            field=models.BooleanField(default=True, help_text='Allow direct UPI ID/QR payment'),
        ),
    ]
