# Generated by Django 5.2.6 on 2026-03-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='options',
            field=models.TextField(blank=True, help_text='Comma-separated options for Select or Radio fields', null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone Number'), ('textarea', 'Textarea'), ('select', 'Select Menu'), ('radio', 'Radio Buttons'), ('date', 'Date Picker'), ('time', 'Time Picker'), ('url', 'Website URL')], max_length=20),
        ),
    ]
