# Generated by Django 5.2.6 on 2026-03-16 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_service_is_online_payment_allowed'),
        ('tokens', '0004_alter_token_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='token',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('service', 'token_number', 'date')},
        ),
    ]
